name: learning-actions

# Controls when the workflow will run
on: push

jobs:
  learning-actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
  test-matron:
    name: test
    needs: learning-actions-job
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"